default_language_version:
  python: python3.12

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
  skip: [ pyproject-fmt, codespell, ruff, ruff-format, mypy ]

exclude: >
  (?x)^(
    \.git/
    | \.idea/
    | \.venv/
    | venv/
    | build/
    | dist/
    | .*\.egg-info/
    | docs/_build/
    | coverage\.xml
    | \.gitignore$
    | LICENSE$
    | .*\.md$
    | .*\.jpg$
    | subprojects/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ --fix=lf ]

  - repo: local
    hooks:
      - id: pyproject-fmt
        name: pyproject-fmt
        entry: pyproject-fmt
        language: system
        files: ^pyproject\.toml$

      - id: codespell
        name: codespell
        entry: codespell
        language: system
        exclude: '.*\.ipynb'
        args: [ "-L", "crate,te,ba,ans,fo,nd" ]

      - id: ruff
        name: ruff
        entry: ruff check --fix --unsafe-fixes
        language: system
        types_or: [ python, pyi, jupyter ]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [ python, pyi, jupyter ]

      - id: mypy
        name: mypy
        entry: mypy --config-file=pyproject.toml
        language: system
        pass_filenames: false
