"""CFFI build script for the vendored UNU.RAN sources."""

from __future__ import annotations

__author__ = "Artem Romanyuk"
__copyright__ = "Copyright (c) 2025 PySATL project"
__license__ = "SPDX-License-Identifier: MIT"

import argparse
import logging
import os
import re
import sys
from pathlib import Path
from typing import Final

from cffi import FFI  # type: ignore[import-untyped]

MODULE_NAME = "pysatl_core.sampling.unuran.bindings._unuran_cffi"
UNURAN_DIR_NAME = "unuran-pysatl"
_CDEF_FILE = Path(__file__).with_name("cffi_unuran.h")
UNURAN_CDEF: Final = _CDEF_FILE.read_text()
UNURAN_EXCLUDED_SOURCE_NAMES: Final = frozenset({"tests.c", "timing.c"})
UNURAN_VERSION: Final = "16:0:0"

UNURAN_CONFIG_DEFINES: Final[dict[str, int | str]] = {
    "HAVE_ALARM": 1,
    "HAVE_DECL_ALARM": 1,
    "HAVE_DECL_HUGE_VAL": 1,
    "HAVE_DECL_HYPOT": 1,
    "HAVE_DECL_INFINITY": 1,
    "HAVE_DECL_ISFINITE": 1,
    "HAVE_DECL_ISINF": 1,
    "HAVE_DECL_ISNAN": 1,
    "HAVE_DECL_LOG1P": 1,
    "HAVE_DECL_SIGNAL": 1,
    "HAVE_DECL_SNPRINTF": 1,
    "HAVE_DECL_VSNPRINTF": 1,
    "HAVE_FLOAT_H": 1,
    "HAVE_FLOOR": 1,
    "HAVE_IEEE_COMPARISONS": 1,
    "HAVE_INTTYPES_H": 1,
    "HAVE_LIBM": 1,
    "HAVE_LIMITS_H": 1,
    "HAVE_POW": 1,
    "HAVE_SIGNAL": 1,
    "HAVE_SQRT": 1,
    "HAVE_STDIO_H": 1,
    "HAVE_STDINT_H": 1,
    "HAVE_STDLIB_H": 1,
    "HAVE_STRCHR": 1,
    "HAVE_STRING_H": 1,
    "HAVE_STRTOL": 1,
    "HAVE_STRTOUL": 1,
    "LT_OBJDIR": "libs/",
    "PACKAGE": "unuran",
    "PACKAGE_BUGREPORT": "unuran@statmath.wu.ac.at",
    "PACKAGE_NAME": "unuran",
    "PACKAGE_STRING": f"unuran {UNURAN_VERSION}",
    "PACKAGE_TARNAME": "unuran",
    "PACKAGE_URL": "",
    "PACKAGE_VERSION": UNURAN_VERSION,
    "UNUR_ENABLE_INFO": 1,
    "VERSION": UNURAN_VERSION,
    "_ISOC99_SOURCE": 1,
}

LOGGER = logging.getLogger(__name__)

ffi = FFI()

ffi.cdef(UNURAN_CDEF)


def _configure_logging(verbose: bool, log_file: str | None = None) -> None:
    """Initialize logging with INFO when verbose and WARNING otherwise.

    Parameters
    ----------
    verbose : bool
        Enable INFO-level logging; WARNING level is used otherwise.
    log_file : str | None
        Path to a file where log output will be written. If ``None``, logs
        are written to stderr only.
    """
    level = logging.INFO if verbose else logging.WARNING
    handlers: list[logging.Handler] = [logging.StreamHandler()]
    if log_file is not None:
        handlers.append(logging.FileHandler(log_file))
    logging.basicConfig(level=level, format="%(levelname)s: %(message)s", handlers=handlers)


def _get_project_root() -> Path:
    """Ascend parent directories to locate the repository containing pyproject.toml."""
    current_file = Path(__file__).resolve()
    current_dir = current_file.parent

    while current_dir != current_dir.parent:
        if (current_dir / "pyproject.toml").exists():
            return current_dir
        current_dir = current_dir.parent

    raise RuntimeError(
        f"Could not find project root (pyproject.toml) starting from {current_file.parent}"
    )


def _extract_library_name(library_path: Path) -> str:
    """Return the bare library name stripping common prefixes/suffixes."""
    name = library_path.name
    if name.startswith("lib"):
        name = name[3:]

    for marker in (".so", ".dylib", ".a", ".dll"):
        if marker in name:
            name = name.split(marker, 1)[0]
            break

    return name or library_path.stem


def _extract_meson_quoted_values(meson_build: str, variable_name: str, call_name: str) -> list[str]:
    """Extract quoted values from a simple Meson assignment call."""
    pattern = re.compile(
        rf"{re.escape(variable_name)}\s*=\s*{re.escape(call_name)}\((.*?)\)",
        flags=re.DOTALL,
    )
    match = pattern.search(meson_build)
    if match is None:
        raise RuntimeError(f"Could not find Meson assignment {variable_name} = {call_name}(...)")

    return re.findall(r"'([^']+)'", match.group(1))


def _format_config_define(name: str, value: int | str) -> str:
    """Format one config.h preprocessor definition."""
    if isinstance(value, int):
        return f"#define {name} {value}"

    escaped_value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'#define {name} "{escaped_value}"'


def _write_config_header(build_dir: Path) -> Path:
    """Write a generated config.h for the vendored UNU.RAN sources."""
    build_dir.mkdir(parents=True, exist_ok=True)
    config_header = build_dir / "config.h"
    lines = [
        "/* Generated by pysatl_core.sampling.unuran.bindings._cffi_build. */",
        "#ifndef PYSATL_UNURAN_CONFIG_H",
        "#define PYSATL_UNURAN_CONFIG_H",
        "",
        *[
            _format_config_define(name, value)
            for name, value in sorted(UNURAN_CONFIG_DEFINES.items())
        ],
        "",
        "#endif",
        "",
    ]
    config_header.write_text("\n".join(lines), encoding="utf-8")
    return config_header


def _collect_unuran_sources(unuran_dir: Path) -> tuple[list[Path], list[Path]]:
    """Collect UNU.RAN C sources and include directories from the vendored Meson file."""
    meson_file = unuran_dir / "meson.build"
    if not meson_file.exists():
        raise RuntimeError(f"Meson file {meson_file} not found")

    meson_build = meson_file.read_text(encoding="utf-8")
    source_paths = [
        (unuran_dir / relative_path).resolve()
        for relative_path in _extract_meson_quoted_values(meson_build, "unuran_sources", "files")
    ]
    include_dirs = [
        (unuran_dir / relative_path).resolve()
        for relative_path in _extract_meson_quoted_values(
            meson_build, "unuran_include_dirs", "include_directories"
        )
    ]

    source_paths = [
        source_path
        for source_path in source_paths
        if source_path.name not in UNURAN_EXCLUDED_SOURCE_NAMES
    ]

    missing_sources = [source_path for source_path in source_paths if not source_path.exists()]
    if missing_sources:
        missing = ", ".join(str(path) for path in missing_sources[:5])
        raise RuntimeError(f"Missing UNU.RAN source files: {missing}")

    missing_include_dirs = [include_dir for include_dir in include_dirs if not include_dir.exists()]
    if missing_include_dirs:
        missing = ", ".join(str(path) for path in missing_include_dirs[:5])
        raise RuntimeError(f"Missing UNU.RAN include directories: {missing}")

    return source_paths, include_dirs


def _compiler_args() -> list[str]:
    """Return compiler arguments for the current platform."""
    if sys.platform == "win32":
        return ["/std:c11", "/O2", "/DHAVE_CONFIG_H=1", "/D_CRT_SECURE_NO_WARNINGS"]

    return ["-std=c99", "-O2", "-DHAVE_CONFIG_H=1"]


def _link_libraries() -> list[str]:
    """Return system libraries required by UNU.RAN."""
    if sys.platform == "win32":
        return []

    return ["m"]


def _configure_from_vendored_sources(unuran_dir: Path, build_dir: Path) -> None:
    """Configure the CFFI module to compile the vendored UNU.RAN sources."""
    config_header = _write_config_header(build_dir)
    source_paths, include_dirs = _collect_unuran_sources(unuran_dir)

    LOGGER.info("Using generated UNU.RAN config at %s", config_header)
    LOGGER.info("Compiling %s UNU.RAN source files", len(source_paths))

    ffi.set_source(
        MODULE_NAME,
        '#include "unuran.h"',
        include_dirs=[
            str(config_header.parent),
            *[str(include_dir) for include_dir in include_dirs],
        ],
        sources=[str(source_path) for source_path in source_paths],
        libraries=_link_libraries(),
        extra_compile_args=_compiler_args(),
    )


def _configure_from_paths(include_file: Path, library_file: Path) -> None:
    """Configure the CFFI module depending on whether the target is static or shared."""
    include_dir = include_file.parent

    if library_file.suffix == ".a":
        LOGGER.info("Linking against static library %s", library_file)
        ffi.set_source(
            MODULE_NAME,
            '#include "unuran.h"',
            include_dirs=[str(include_dir)],
            extra_objects=[str(library_file)],
            extra_compile_args=["-std=c99", "-O2"],
        )
        return

    library_name = _extract_library_name(library_file)
    library_dir = library_file.parent

    LOGGER.info("Linking against shared library %s", library_file)
    ffi.set_source(
        MODULE_NAME,
        '#include "unuran.h"',
        include_dirs=[str(include_dir)],
        libraries=[library_name],
        library_dirs=[str(library_dir)],
        extra_compile_args=["-std=c99"],
    )


def find_unuran(unuran_dir: Path, raise_on_error: bool = True) -> dict[str, Path | None]:
    """
    Locate the UNU.RAN library and its header file within the submodules tree.

    Parameters
    ----------
    unuran_dir : Path
        Root of the vendored UNU.RAN source tree.
    raise_on_error : bool, default True
        When ``True``, raise :exc:`ImportError` if either the header or the
        library file cannot be found. When ``False``, return ``None`` values
        for missing paths without raising.

    Returns
    -------
    dict[str, Path | None]
        Dictionary with keys ``"include_path"`` and ``"library_path"``,
        each holding a resolved :class:`Path` or ``None`` if not found.

    Raises
    ------
    ImportError
        If ``raise_on_error`` is ``True`` and the library or header is missing.
    """
    results: dict[str, Path | None] = {
        "include_path": None,
        "library_path": None,
    }

    possible_lib_paths = [
        unuran_dir / "out" / "libunuran.a",  # Windows + Linux
        unuran_dir / "out" / "libunuran.so",  # Linux
        unuran_dir / "out" / "libunuran.dylib",  # macOS
    ]

    for path in possible_lib_paths:
        if path and path.exists():
            results["library_path"] = path.resolve()
            break

    include_path = unuran_dir / "unuran" / "src" / "unuran.h"

    if include_path.exists():
        results["include_path"] = include_path

    if not results["library_path"] and raise_on_error:
        raise ImportError("libunuran.so not found")

    if not results["include_path"] and raise_on_error:
        raise ImportError("Header unuran.h not found")

    return results


def build_unuran(unuran_dir: Path) -> None:
    """
    Validate that the vendored UNU.RAN sources are available.

    The C sources are compiled directly into the CFFI extension during wheel
    build, so no separate static or shared library is produced here.

    Parameters
    ----------
    unuran_dir : Path
        Root of the vendored UNU.RAN source tree.

    Raises
    ------
    RuntimeError
        If the vendored source tree is incomplete.
    """
    _collect_unuran_sources(unuran_dir)


def main() -> None:
    """
    Entry point for the CFFI build: locate UNU.RAN, configure the extension,
    and compile the ``_unuran_cffi`` module into ``src/``.

    Raises
    ------
    RuntimeError
        If UNU.RAN cannot be found after attempting the build.
    """
    project_root = _get_project_root()
    unuran_dir = project_root / "subprojects" / UNURAN_DIR_NAME
    build_unuran(unuran_dir)
    _configure_from_vendored_sources(unuran_dir, project_root / "build" / "unuran")

    build_output_dir = project_root / "src"
    previous_cwd = Path.cwd()

    try:
        os.chdir(build_output_dir)
        ffi.compile(verbose=True)
    finally:
        os.chdir(previous_cwd)

    LOGGER.info("CFFI bindings compiled successfully.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build CFFI bindings for the vendored UNU.RAN library."
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        default=False,
        help="Enable INFO-level logging during the build.",
    )
    parser.add_argument(
        "--log-file",
        metavar="PATH",
        default=None,
        help="Write log output to PATH in addition to stderr.",
    )
    args = parser.parse_args()
    _configure_logging(args.verbose, args.log_file)
    main()
